trigger:
  branches:
    include:
    - master
  
stages:
- stage: default

  jobs:
    - job: Job
      pool:
        vmImage: 'ubuntu-latest'

      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'
      
      - script: |
          npm install -g @angular/cli
          npm install
          ng build --prod
        displayName: 'npm install and build'
      
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'dist/ngBuild'
          ArtifactName: 'ngapp'
          publishLocation: 'Container'
        displayName: 'Publish Artifacts'